version: '3.1'

services:

#  postgres:
#    image: postgres:12.4
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: S4TeAmGS
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mrsalwaysright201096
    ports:
      - 3308:3306
    volumes:
      - ./data/db:/var/lib/mysql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
