server:
  port: 8080

okta:
  client:
    org-url: https://dev-82681560.okta.com
    token: 00oGTBzHlnsYVwQn451lJXawVvdXGN_CCNnnrHCEv8
  oauth2:
    client-id: 0oaao4okyxBjfnMwg5d6
    client-secret: 6OBFxCr4wspkQTAK1I2rMh0FxT3vPLiiVlDz91cA
    issuer: https://dev-82681560.okta.com/oauth2/default

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/competencemap?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    password: "Mrsalwaysright201096"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

  profiles:
    active: dev

  flyway:
    locations: [ "classpath:db/migration" ]
    table: schema_version
    baseline-on-migrate: true

logging:
  config: classpath:log4j2.config/log4j2-dev.xml

allowed-origins: http://localhost:4200, http://mydomain, https://mydomain
