server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/competencemap?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    password: "Mrsalwaysright201096"
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: true

  profiles:
    active: dev

  flyway:
    locations: [ "classpath:db/migration" ]
    table: schema_version
    baseline-on-migrate: true

logging:
  config: classpath:log4j2.config/log4j2-dev.xml

allowed-origin: http://45.61.48.40:4200
