INSERT INTO skills_n_knowledge(id, title, type, e_competence_id)
VALUES
    ('A.01.K1', 'K1 business strategy concepts', 'K', 'A.01'),
    ('A.01.K2', 'K2 trends and implications of ICT internal or external developments for typical organisations ', 'K', 'A.01'),
    ('A.01.K3', 'K3 the potential and opportunities of relevant business models', 'K', 'A.01'),
    ('A.01.K4', 'K4 the business aims and organisational objectives ', 'K', 'A.01'),
    ('A.01.K5', 'K5 the issues and implications of sourcing models ', 'K', 'A.01'),
    ('A.01.K6', 'K6 the new emerging technologies (e.g. distributed systems, virtualisation, mobility, data sets) ', 'K', 'A.01'),
    ('A.01.K7', 'K7 architectural frameworks ', 'K', 'A.01'),
    ('A.01.K8', 'K8 security', 'K', 'A.01'),
    ('A.01.S1', 'S1 analyse future developments in business process and technology application ', 'S', 'A.01'),
    ('A.01.S2', 'S2 determine requirements for processes related to ICT services ', 'S', 'A.01'),
    ('A.01.S3', 'S3 identify and analyse long term user / customer needs ', 'S', 'A.01'),
    ('A.01.S4', 'S4 contribute to the development of ICT strategy and policy, including ICT security and quality ', 'S', 'A.01'),
    ('A.01.S5', 'S5 contribute to the development of the business strategy ', 'S', 'A.01'),
    ('A.01.S6', 'S6 analyse feasibility in terms of costs and benefits ', 'S', 'A.01'),
    ('A.01.S7', 'S7 review and analyse effects of implementations ', 'S', 'A.01'),
    ('A.01.S8', 'S8 understand the impact of new technologies on business (e.g. open / big data, dematerialisation opportunities and strategies) ', 'S', 'A.01'),
    ('A.01.S9', 'S9 understand the business benefits of new technologies and how this can add value and provide competitive advantage (e.g. open / big data, dematerialisation opportunities and strategies) ', 'S', 'A.01'),
    ('A.01.S10', 'S10 understand the enterprise architecture ', 'S', 'A.01'),
    ('A.01.S11', 'S11 understand the legal & regulatory landscape in order to factor into business requirements', 'S', 'A.01'),

    ('A.02.K1', 'K1 SLA documentation', 'K', 'A.02'),
    ('A.02.K2', 'K2 how to compare and interpret management data', 'K', 'A.02'),
    ('A.02.K3', 'K3 the elements forming the metrics of service level agreements', 'K', 'A.02'),
    ('A.02.K4', 'K4 how service delivery infrastructures work', 'K', 'A.02'),
    ('A.02.K5', 'K5 impact of service level non-compliance on business performance', 'K', 'A.02'),
    ('A.02.K6', 'K6 ICT security standards', 'K', 'A.02'),
    ('A.02.K7', 'K7 ICT quality standards', 'K', 'A.02'),
    ('A.02.S1', 'S1 analyse service provision records', 'S', 'A.02'),
    ('A.02.S2', 'S2 evaluate service provision against SLA', 'S', 'A.02'),
    ('A.02.S3', 'S3 negotiate realistic service level targets', 'S', 'A.02'),
    ('A.02.S4', 'S4 use relevant quality management techniques', 'S', 'A.02'),
    ('A.02.S5', 'S5 anticipate and mitigate against potential service disruptions', 'S', 'A.02'),

    ('A.03.K1', 'K1 business plan elements and milestones ', 'K', 'A.03'),
    ('A.03.K2', 'K2 the present and future market size and needs ', 'K', 'A.03'),
    ('A.03.K3', 'K3 competition and SWOT analysis techniques (for product features and also the external environment) ', 'K', 'A.03'),
    ('A.03.K4', 'K4 value creation channels ', 'K', 'A.03'),
    ('A.03.K5', 'K5 profitability elements ', 'K', 'A.03'),
    ('A.03.K6', 'K6 the issues and implications of sourcing models ', 'K', 'A.03'),
    ('A.03.K7', 'K7 financial planning and dynamic ', 'K', 'A.03'),
    ('A.03.K8', 'K8 new emerging technologies ', 'K', 'A.03'),
    ('A.03.K9', 'K9 risk and opportunity assessment techniques ', 'K', 'A.03'),
    ('A.03.S1', 'S1 address and identify essential elements of product or solution value propositions ', 'S', 'A.03'),
    ('A.03.S2', 'S2 define the appropriate value creation channels ', 'S', 'A.03'),
    ('A.03.S3', 'S3 build a detailed SWOT analysis ', 'S', 'A.03'),
    ('A.03.S4', 'S4 generate short and long term performance reports (e.g. financial, profitability, usage and value creation) ', 'S', 'A.03'),
    ('A.03.S5', 'S5 identify main milestones of the plan', 'S', 'A.03'),

    ('A.04.K1', 'K1 effective frameworks and methodologies for governance plans ', 'K', 'A.04'),
    ('A.04.K2', 'K2 typical KPI (key performance indicators) ', 'K', 'A.04'),
    ('A.04.K3', 'K3 basic decision-making methods ', 'K', 'A.04'),
    ('A.04.K4', 'K4 IPR principles and regulation ', 'K', 'A.04'),
    ('A.04.K5', 'K5 agile techniques ', 'K', 'A.04'),
    ('A.04.K6', 'K6 structured Project Management Methodologies (e.g. agile techniques) ', 'K', 'A.04'),
    ('A.04.K7', 'K7 optimisation methods (e.g. lean management) ', 'K', 'A.04'),
    ('A.04.K8', 'K8 new emerging technologies ', 'K', 'A.04'),
    ('A.04.S1', 'S1 identify all potential targets for the product or service ', 'S', 'A.04'),
    ('A.04.S2', 'S2 define the communication plan; identify key users and create related documentation ', 'S', 'A.04'),
    ('A.04.S3', 'S3 produce quality plans ', 'S', 'A.04'),
    ('A.04.S4', 'S4 ensure and manage adequate information for decision makers ', 'S', 'A.04'),
    ('A.04.S5', 'S5 manage the change request process ', 'S', 'A.04'),
    ('A.04.S6', 'S6 manage the product / service development management lifecycle (inclusive of the formal change request process) ', 'S', 'A.04'),


    ('A.05.K1', 'K1 architecture frameworks, methodologies and systems design tools ', 'K', 'A.05'),
    ('A.05.K2', 'K2 systems architecture requirements: performance, maintainability, extendibility, scalability, availability, security and accessibility ', 'K', 'A.05'),
    ('A.05.K3', 'K3 costs, benefits and risks of a system architecture ', 'K', 'A.04'),
    ('A.05.K4', 'K4 the company’s enterprise architecture and internal standards ', 'K', 'A.05'),
    ('A.05.K5', 'K5 new emerging technologies (e.g., distributed systems, virtualisation models, datasets, mobile systems)', 'K', 'A.05'),
    ('A.05.S1', 'S1 provide expertise to help solve complex technical problems and ensure best architecture solutions are implemented ', 'S', 'A.05'),
    ('A.05.S2', 'S2 use knowledge in various technology areas to build and deliver the enterprise architecture ', 'S', 'A.05'),
    ('A.05.S3', 'S3 understand the business objectives / drivers that impact the architecture component (data, application, security, development etc) ', 'S', 'A.05'),
    ('A.05.S4', 'S4 assist in communication of the enterprise architecture and standards, principles and objectives to the application teams ', 'S', 'A.05'),
    ('A.05.S5', 'S5 develop design patterns and models to assist system analysts in designing consistent applications ', 'S', 'A.05'),

    ('A.06.K1', 'K1 requirements modelling and need analysis techniques ', 'K', 'A.06'),
    ('A.06.K2', 'K2 software developments methods and their rationale (e.g. prototyping, agile methods, reverse engineering, etc.) ', 'K', 'A.06'),
    ('A.06.K3', 'K3 metrics related to application development ', 'K', 'A.06'),
    ('A.06.K4', 'K4 user interface design principles ', 'K', 'A.06'),
    ('A.06.K5', 'K5 languages for formalising functional specification ', 'K', 'A.06'),
    ('A.06.K6', 'K6 existing applications and related architecture ', 'K', 'A.06'),
    ('A.06.K7', 'K7 DBMS, Data Warehouse, DSS … etc ', 'K', 'A.06'),
    ('A.06.K8', 'K8 mobile technologies ', 'K', 'A.06'),
    ('A.06.K9', 'K9 threat modelling techniques ', 'K', 'A.06'),
    ('A.06.S1', 'S1 identify customers, users & stakeholders ', 'S', 'A.06'),
    ('A.06.S2', 'S2 collect, formalise and validate functional and no-functional requirements ', 'S', 'A.06'),
    ('A.06.S3', 'S3 apply estimation models and data to evaluate costs of different software lifecycle phases ', 'S', 'A.06'),
    ('A.06.S4', 'S4 evaluate the use of prototypes to support requirements validation ', 'S', 'A.06'),
    ('A.06.S5', 'S5 design, organise and monitor the overall plan for the design of application ', 'S', 'A.06'),
    ('A.06.S6', 'S6 design functional specification starting from defined requirements ', 'S', 'A.06'),
    ('A.06.S7', 'S7 evaluate the suitability of different application development methods for the current scenario ', 'S', 'A.06'),
    ('A.06.S8', 'S8 establish systematic and frequent communication with customers, users and stakeholders ', 'S', 'A.06'),
    ('A.06.S9', 'S9 ensure that controls & functionality are built in to the design ', 'S', 'A.06'),

    ('A.07.K1', 'K1 emerging technologies and the relevant market applications ', 'K', 'A.07'),
    ('A.07.K2', 'K2 market needs ', 'K', 'A.07'),
    ('A.07.K3', 'K3 relevant sources of information (e.g. magazines, conferences and events, newsletters, opinion leaders, on-line forum, etc.) ', 'K', 'A.07'),
    ('A.07.K4', 'K4 the rules of discussions in web communities ', 'K', 'A.07'),
    ('A.07.K5', 'K5 applied research programme approaches', 'K', 'A.07'),
    ('A.07.S1', 'S1 monitor sources of information and continuously follow the most promising ', 'S', 'A.07'),
    ('A.07.S2', 'S2 identify vendors and providers of the most promising solutions; evaluate, justify and propose the most appropriate. ', 'S', 'A.07'),
    ('A.07.S3', 'S3 identify business advantages and improvements of adopting emerging technologies', 'S', 'A.07'),

    ('A.08.K1', 'K1 metrics and indicators related to sustainable development ', 'K', 'A.08'),
    ('A.08.K2', 'K2 corporate social responsibility (CSR) of stakeholders within the IS infrastructure', 'K', 'A.08'),
    ('A.08.S1', 'S1 monitor and measure the ICT energy consumption ', 'S', 'A.08'),
    ('A.08.S2', 'S2 apply recommendations in projects to support latest sustainable development strategies ', 'S', 'A.08'),
    ('A.08.S3', 'S3 master regulatory constraints and international standards related to ICT sustainability', 'S', 'A.08'),

    ('A.09.K1', 'K1 existing and emerging technologies and market applications ', 'K', 'A.09'),
    ('A.09.K2', 'K2 business, society and /or research habits, trends and needs ', 'K', 'A.09'),
    ('A.09.K3', 'K3 innovation processes techniques ', 'K', 'A.09'),
    ('A.09.S1', 'S1 identify business advantages and improvements of adopting emerging technologies ', 'S', 'A.09'),
    ('A.09.S2', 'S2 create a proof of concept ', 'S', 'A.09'),
    ('A.09.S3', 'S3 think out of the box ', 'S', 'A.09'),
    ('A.09.S4', 'S4 identify appropriate resources ', 'S', 'A.09'),

    ('B.01.K1', 'K1 appropriate software programs /modules ', 'K', 'B.01'),
    ('B.01.K2', 'K2 hardware components, tools and hardware architectures ', 'K', 'B.01'),
    ('B.01.K3', 'K3 functional & technical designing ', 'K', 'B.01'),
    ('B.01.K4', 'K4 state of the art technologies ', 'K', 'B.01'),
    ('B.01.K5', 'K5 programming languages ', 'K', 'B.01'),
    ('B.01.K6', 'K6 Power consumption models of software and / or hardware ', 'K', 'B.01'),
    ('B.01.K7', 'K7 DBMS ', 'K', 'B.01'),
    ('B.01.K8', 'K8 operating Systems and software platforms ', 'K', 'B.01'),
    ('B.01.K9', 'K9 Integrated development environment (IDE) ', 'K', 'B.01'),
    ('B.01.K10', 'K10 rapid application development (RAD) ', 'K', 'B.01'),
    ('B.01.K11', 'K11 IPR issues ', 'K', 'B.01'),
    ('B.01.K12', 'K12 modeling technology and languages ', 'K', 'B.01'),
    ('B.01.K13', 'K13 interface definition languages (IDL) ', 'K', 'B.01'),
    ('B.01.K14', 'K14 security ', 'K', 'B.01'),
    ('B.01.S1', 'S1 explain and communicate the design / development to the customer ', 'S', 'B.01'),
    ('B.01.S2', 'S2 perform and evaluate test results against product specifications ', 'S', 'B.01'),
    ('B.01.S3', 'S3 apply appropriate software and / or hardware architectures ', 'S', 'B.01'),
    ('B.01.S4', 'S4 develop user interfaces, business software components and embedded software components ', 'S', 'B.01'),
    ('B.01.S5', 'S5 manage and guarantee high levels of cohesion and quality ', 'S', 'B.01'),
    ('B.01.S6', 'S6 use data models ', 'S', 'B.01'),
    ('B.01.S7', 'S7 perform and evaluate test in the customer or target environment ', 'S', 'B.01'),
    ('B.01.S8', 'S8 cooperate with development team and with application designers ', 'S', 'B.01'),

    ('B.02.K1', 'K1 old, existing and new hardware components / software programs / modules ', 'K', 'B.02'),
    ('B.02.K2', 'K2 the impact that system integration has on existing system / organisation ', 'K', 'B.02'),
    ('B.02.K3', 'K3 interfacing techniques between modules, systems and components ', 'K', 'B.02'),
    ('B.02.K4', 'K4 integration testing techniques ', 'K', 'B.02'),
    ('B.02.K5', 'K5 development tools (e.g. development environment, management, source code access / revision control) ', 'K', 'B.02'),
    ('B.02.K6', 'K6 best practice design techniques ', 'K', 'B.02'),
    ('B.02.S1', 'S1 measure system performance before, during and after system integration ', 'S', 'B.02'),
    ('B.02.S2', 'S2 document and record activities, problems and related repair activities ', 'S', 'B.02'),
    ('B.02.S3', 'S3 match customers’ needs with existing products ', 'S', 'B.02'),
    ('B.02.S4', 'S4 verify that integrated systems capabilities and efficiency match specifications ', 'S', 'B.02'),
    ('B.02.S5', 'S5 secure / back-up data to ensure integrity during system integration ', 'S', 'B.02'),

    ('B.03.K1', 'K1 techniques, infrastructure and tools to be used in the testing process ', 'K', 'B.03'),
    ('B.03.K2', 'K2 the lifecycle of a testing process ', 'K', 'B.03'),
    ('B.03.K3', 'K3 the different sorts of tests (functional, integration, performance, usability, stress etc.) ', 'K', 'B.03'),
    ('B.03.K4', 'K4 national and international standards defining quality criteria for testing ', 'K', 'B.03'),
    ('B.03.K5', 'K5 web, cloud and mobile technologies and environmental requirements ', 'K', 'B.03'),
    ('B.03.S1', 'S1 create and manage a test plan ', 'S', 'B.03'),
    ('B.03.S2', 'S2 manage and evaluate the test process ', 'S', 'B.03'),
    ('B.03.S3', 'S3 design tests of ICT systems ', 'S', 'B.03'),
    ('B.03.S4', 'S4 prepare and conduct tests of ICT systems ', 'S', 'B.03'),
    ('B.03.S5', 'S5 report and document tests and results ', 'S', 'B.03'),

    ('B.04.K1', 'K1 performance analysis techniques ', 'K', 'B.04'),
    ('B.04.K2', 'K2 techniques related to problem management (operation, performance, compatibility) ', 'K', 'B.04'),
    ('B.04.K3', 'K3 software packaging and distribution methods and techniques ', 'K', 'B.04'),
    ('B.04.K4', 'K4 the impacts of deployment on the current architecture ', 'K', 'B.04'),
    ('B.04.K5', 'K5 the technologies and standards to be used during the deployment ', 'K', 'B.04'),
    ('B.04.K6', 'K6 web, cloud and mobile technologies and environmental requirements ', 'K', 'B.04'),
    ('B.04.S1', 'S1 organise deployment workflow and product roll-out activities ', 'S', 'B.04'),
    ('B.04.S2', 'S2 organise and plan beta-test activities, testing solution in its final operational environment ', 'S', 'B.04'),
    ('B.04.S3', 'S3 configure components at any level to guarantee correct overall interoperability ', 'S', 'B.04'),
    ('B.04.S4', 'S4 identify and engage expertise needed to solve interoperability problems ', 'S', 'B.04'),
    ('B.04.S5', 'S5 organise and control initial support service provision including user training during system start-up ', 'S', 'B.04'),
    ('B.04.S6', 'S6 organise population of data bases and manage data migration ', 'S', 'B.04'),
    ('B.04.S7', 'S7 collaborate to modify 3rd party code; support and maintain modified software ', 'S', 'B.04'),

    ('B.05.K1', 'K1 tools for production, editing and distribution of professional documents ', 'K', 'B.05'),
    ('B.05.K2', 'K2 tools for multimedia presentation creation ', 'K', 'B.05'),
    ('B.05.K3', 'K3 different technical documents required for designing, developing and deploying products, applications and services ', 'K', 'B.05'),
    ('B.05.K4', 'K4 version control of documentation production ', 'K', 'B.05'),
    ('B.05.S1', 'S1 observe and deploy effective use of corporate standards for publications ', 'S', 'B.05'),
    ('B.05.S2', 'S2 prepare templates for shared publications ', 'S', 'B.05'),
    ('B.05.S3', 'S3 organise and control content management workflow ', 'S', 'B.05'),
    ('B.05.S4', 'S4 keep publications aligned to the solution during the entire lifecycle ', 'S', 'B.05'),

    ('B.06.K1', 'K1 appropriate software programs /modules, DBMS and programming languages ', 'K', 'B.06'),
    ('B.06.K2', 'K2 hardware components, tools and hardware architectures ', 'K', 'B.06'),
    ('B.06.K3', 'K3 functional & technical designing ', 'K', 'B.06'),
    ('B.06.K4', 'K4 state of the art technologies ', 'K', 'B.06'),
    ('B.06.K5', 'K5 programming languages ', 'K', 'B.06'),
    ('B.06.K6', 'K6 power consumption models of software and / or hardware ', 'K', 'B.06'),
    ('B.06.K7', 'K7 information Security Basics ', 'K', 'B.06'),
    ('B.06.K8', 'K8 prototyping ', 'K', 'B.06'),
    ('B.06.S1', 'S1 explain and communicate the design / development to the customer ', 'S', 'B.06'),
    ('B.06.S2', 'S2 perform and evaluate test results against product specifications ', 'S', 'B.06'),
    ('B.06.S3', 'S3 apply appropriate software and / or hardware architectures ', 'S', 'B.06'),
    ('B.06.S4', 'S4 design and develop hardware architecture, user interfaces, business software components and embedded software components ', 'S', 'B.06'),
    ('B.06.S5', 'S5 manage and guarantee high levels of cohesion and quality in complex software developments ', 'S', 'B.06'),
    ('B.06.S6', 'S6 use data models ', 'S', 'B.06'),
    ('B.06.S7', 'S7 apply appropriate development and / or process models, to develop effectively and efficiently ', 'S', 'B.06'),

    ('C.01.K1', 'K1 relevant ICT user applications ', 'K', 'C.01'),
    ('C.01.K2', 'K2 database structures and content organisation ', 'K', 'C.01'),
    ('C.01.K3', 'K3 corporate escalation procedures ', 'K', 'C.01'),
    ('C.01.K4', 'K4 software distribution methods and procedures for fix application and file transmission methodologies applicable to software fixes ', 'K', 'C.01'),
    ('C.01.K5', 'K5 sources of information for potential solutions ', 'K', 'C.01'),
    ('C.01.S1', 'S1 effectively interrogate users to establish symptoms ', 'S', 'C.01'),
    ('C.01.S2', 'S2 analyse symptoms to identify broad area of user error or technical failure ', 'S', 'C.01'),
    ('C.01.S3', 'S3 deploy support tools to systematically trace source of error or technical failure ', 'S', 'C.01'),
    ('C.01.S4', 'S4 clearly communicate with end users and provide instructions on how to progress issues ', 'S', 'C.01'),
    ('C.01.S5', 'S5 record and code issues to support growth and integrity of online support tools ', 'S', 'C.01'),

    ('C.02.K1', 'K1 functional specifications of the information system', 'K', 'C.02'),
    ('C.02.K2', 'K2 the existing ICT application technical architecture', 'K', 'C.02'),
    ('C.02.K3', 'K3 how business processes are integrated and their dependency upon ICT applications', 'K', 'C.02'),
    ('C.02.K4', 'K4 change management tools and technique', 'K', 'C.02'),
    ('C.02.K5', 'K5 the best practices and standards in information security management', 'K', 'C.02'),
    ('C.02.S1', 'S1 share functional and technical specifications with ICT teams in charge of the maintenance and  evolution of ICT solutions', 'S', 'C.02'),
    ('C.02.S2', 'S2 manage communications with ICT teams in charge of the maintenance and the evolution of information systems solutions', 'S', 'C.02'),
    ('C.02.S3', 'S3 analyse the impact of functional/technical changes on users', 'S', 'C.02'),
    ('C.02.S4', 'S4 anticipate all actions required to mitigate the impact of changes (training,  documentation, new processes…).', 'S', 'C.02'),

    ('C.03.K1', 'K1 how to interpret ICT service delivery requirements  ', 'K', 'C.03'),
    ('C.03.K2', 'K2 best practices and standards in ICT service delivery.', 'K', 'C.03'),
    ('C.03.K3', 'K3 how to monitor service delivery', 'K', 'C.03'),
    ('C.03.K4', 'K4 how to record service delivery actions and able to identify failures ', 'K', 'C.03'),
    ('C.03.K5', 'K5 the best practices and standards in information security management ', 'K', 'C.03'),
    ('C.03.K6', 'K6 web, cloud and mobile technologies ', 'K', 'C.03'),
    ('C.03.S1', 'S1 apply the processes which comprise the organisations ICT service delivery strategy', 'S', 'C.03'),
    ('C.03.S2', 'S2 fill in and complete documentation used in  ICT service delivery', 'S', 'C.03'),
    ('C.03.S3', 'S3 analyse service delivery provision and report outcomes to senior colleagues ', 'S', 'C.03'),
    ('C.03.S4', 'S4 plan and apply manpower workload/requirements for efficient and cost effective service provision', 'S', 'C.03'),
       
    ('C.04.K1', 'K1 the organisation’s overall ICT infrastructure and key components', 'K', 'C.04'),
    ('C.04.K2', 'K2 the organisation’s reporting procedures', 'K', 'C.04'),
    ('C.04.K3', 'K3 the organisation’s critical situation escalation procedures', 'K', 'C.04'),
    ('C.04.K4', 'K4 the application and availability of diagnostic tools', 'K', 'C.04'),
    ('C.04.K5', 'K5 the link between system infrastructure elements and impact of failure on related business processes.', 'K', 'C.04'),
    ('C.04.S1', 'S1 monitor progress of issues throughout lifecycle and communicate effectively', 'S', 'C.04'),
    ('C.04.S2', 'S2 identify potential critical component failures and take action to mitigate effects of failure', 'S', 'C.04'),
    ('C.04.S3', 'S3 conduct risk management audits and act to minimise exposures', 'S', 'C.04'),
    ('C.04.S4', 'S4 allocate appropriate resources to maintenance activities, balancing cost and risk', 'S', 'C.04'),
    ('C.04.S5', 'S5 communicate at all levels to ensure appropriate resources are deployed internally or externally to minimise outages', 'S', 'C.04'),

    ('D.01.K1', 'K1 the potential and opportunities of relevant standards and best practices ', 'K', 'D.01'),
    ('D.01.K2', 'K2 the impact of legal requirements on information security ', 'K', 'D.01'),
    ('D.01.K3', 'K3 the information strategy of the organisation ', 'K', 'D.01'),
    ('D.01.K4', 'K4 possible security threats ', 'K', 'D.01'),
    ('D.01.K5', 'K5 the mobility strategy ', 'K', 'D.01'),
    ('D.01.K6', 'K6 the different service models (SaaS, PaaS, IaaS) and operational translations (i.e. Cloud Computing) ', 'K', 'D.01'),
    ('D.01.S1', 'S1 develop and critically analyse the company strategy for information security ', 'S', 'D.01'),
    ('D.01.S2', 'S2 define, present and promote an information security policy for approval by the senior management of the organisation ', 'S', 'D.01'),
    ('D.01.S3', 'S3 apply relevant standards, best practices and legal requirements for information security ', 'S', 'D.01'),
    ('D.01.S4', 'S4 anticipate required changes to the organisation’s information security strategy and formulate new plans ', 'S', 'D.01'),
    ('D.01.S5', 'S5 propose effective contingency measures ', 'S', 'D.01'),

    ('D.02.K1', 'K1 the major information technology industry frameworks, e.g. COBIT, ITIL, CMMI, ISO – and their implications for corporate IS governance ', 'K', 'D.02'),
    ('D.02.K2', 'K2 the information strategy of the organisation ', 'K', 'D.02'),
    ('D.02.K3', 'K3 the different service models (SaaS, PaaS, IaaS) and operational translations (i.e. Cloud Computing) ', 'K', 'D.02'),
    ('D.02.S1', 'S1 define an ICT quality policy to meet the organisation’s standards of performance and customer satisfaction objectives ', 'S', 'D.02'),
    ('D.02.S2', 'S2 identify quality metrics to be used ', 'S', 'D.02'),
    ('D.02.S3', 'S3 apply relevant standards and best practices to maintain information quality ', 'S', 'D.02'),


    ('D.03.K1', 'K1 appropriate pedagogical approaches and education delivery methods e.g. classroom, online, text, dvd ', 'K', 'D.03'),
    ('D.03.K2', 'K2 the competitive market for educational offering ', 'K', 'D.03'),
    ('D.03.K3', 'K3 training needs analysis methodologies ', 'K', 'D.03'),
    ('D.03.K4', 'K4 empowerment techniques ', 'K', 'D.03'),
    ('D.03.S1', 'S1 organise training and education schedules to meet market needs ', 'S', 'D.03'),
    ('D.03.S2', 'S2 identify and maximise use of resources required to deliver a cost effective schedule ', 'S', 'D.03'),
    ('D.03.S3', 'S3 promote and market education and training provision ', 'S', 'D.03'),
    ('D.03.S4', 'S4 analyse feedback data and use it to drive continuous improvement of education and training delivery ', 'S', 'D.03'),
    ('D.03.S5', 'S5 design curricula and training programmes to meet customer ICT education needs ', 'S', 'D.03'),
    ('D.03.S6', 'S6 address CPD needs of staff to meet organisational requirements ', 'S', 'D.03'),

    ('D.04.K1', 'K1 typical purchase contract terms and conditions ', 'K', 'D.04'),
    ('D.04.K2', 'K2 own organisation purchasing policies ', 'K', 'D.04'),
    ('D.04.K3', 'K3 financial models e.g. discount structures ', 'K', 'D.04'),
    ('D.04.K4', 'K4 the current market for relevant products or services ', 'K', 'D.04'),
    ('D.04.K5', 'K5 the issues and implications of outsourcing services ', 'K', 'D.04'),
    ('D.04.K6', 'K6 different service models (SaaS, PaaS, IaaS) and operational translations (e.g. Cloud Computing) ', 'K', 'D.04'),
    ('D.04.S1', 'S1 interpret product / service specifications ', 'S', 'D.04'),
    ('D.04.S2', 'S2 negotiate terms, conditions and pricing ', 'S', 'D.04'),
    ('D.04.S3', 'S3 analyse received proposals/ offers ', 'S', 'D.04'),
    ('D.04.S4', 'S4 manage the purchasing budget ', 'S', 'D.04'),
    ('D.04.S5', 'S5 lead purchase process improvement ', 'S', 'D.04'),
    ('D.04.S6', 'S6 analyse the energy efficiency and environmental-related aspects of a proposal ', 'S', 'D.04'),
    ('D.04.S7', 'S7 verify that purchasing processes respect legal issues including IPR ', 'S', 'D.04'),
       
    ('D.05.K1', 'K1 customer needs ', 'K', 'D.05'),
    ('D.05.K2', 'K2 internally adopted sales and marketing techniques ', 'K', 'D.05'),
    ('D.05.K3', 'K3 legal requirements ', 'K', 'D.05'),
    ('D.05.K4', 'K4 internal business practices ', 'K', 'D.05'),
    ('D.05.K5', 'K5 product or service unique selling points ', 'K', 'D.05'),
    ('D.05.K6', 'K6 the different service models (SaaS, PaaS, IaaS) and operational translations (e.g. Cloud Computing) ', 'K', 'D.05'),
    ('D.05.S1', 'S1 construct the framework for proposal documentation ', 'S', 'D.05'),
    ('D.05.S2', 'S2 co-ordinate and facilitate multidisciplinary teams contributing to the proposal ', 'S', 'D.05'),
    ('D.05.S3', 'S3 interpret the terms and conditions of the tender documentation ', 'S', 'D.05'),
    ('D.05.S4', 'S4 evaluate the strengths and weaknesses of potential competitors ', 'S', 'D.05'),
    ('D.05.S5', 'S5 ensure that a proposal is of high quality and is submitted on time ', 'S', 'D.05'),
    ('D.05.S6', 'S6 communicates the energy efficiency and environmental-related aspects of a proposal ', 'S', 'D.05'),
    ('D.05.S7', 'S7 ensure that proposals meet compliance requirements ', 'S', 'D.05'),
       
    ('D.06.K1', 'K1 the competition (what and where) ', 'K', 'D.06'),
    ('D.06.K2', 'K2 the market distribution across the field ', 'K', 'D.06'),
    ('D.06.K3', 'K3 sales channel typologies (e.g. direct sales, VAR, web marketing) ', 'K', 'D.06'),
    ('D.06.K4', 'K4 incentive policies ', 'K', 'D.06'),
    ('D.06.K5', 'K5 user experience of each channel type ', 'K', 'D.06'),
    ('D.06.K6', 'K6 legal issues relating to channels and VAR organisations ', 'K', 'D.06'),
    ('D.06.S1', 'S1 choose the best sales channel according to the product or solution being delivered ', 'S', 'D.06'),
    ('D.06.S2', 'S2 define discounts according to the competitive environment ', 'S', 'D.06'),
    ('D.06.S3', 'S3 select value added retailers based on thorough analyses, plan and make contacts ', 'S', 'D.06'),
    ('D.06.S4', 'S4 monitor and supervise channel performances in line with sales forecast and able to define corrective actions if necessary ', 'S', 'D.06'),
    ('D.06.S5', 'S5 apply digital marketing methods ', 'S', 'D.06'),
       
    ('D.07.K1', 'K1 customer organisation (needs, budget allocation and decision makers) ', 'K', 'D.07'),
    ('D.07.K2', 'K2 company specific processes (sales, ITIL, etc.) ', 'K', 'D.07'),
    ('D.07.K3', 'K3 market trends and own service offering portfolio ', 'K', 'D.07'),
    ('D.07.K4', 'K4 legal, financial and contractual rules ', 'K', 'D.07'),
    ('D.07.K5', 'K5 project management procedures ', 'K', 'D.07'),
    ('D.07.K6', 'K6 current market imperatives e.g. risks, changes, innovation ', 'K', 'D.07'),
    ('D.07.S1', 'S1 develop strong co-operation between customers and own organisation ', 'S', 'D.07'),
    ('D.07.S2', 'S2 keep abreast of market news e.g. risks, changes, innovations and communicate to internal business units, to improve service and product portfolio ', 'S', 'D.07'),
    ('D.07.S3', 'S3 react proactively to customer business changes and communicate them internally ', 'S', 'D.07'),
    ('D.07.S4', 'S4 generate sustainable customer relationships ', 'S', 'D.07'),
    ('D.07.S5', 'S5 analyse sales performance to build forecasts and develop a tactical sales plan ', 'S', 'D.07'),

    ('D.08.K1', 'K1 applicable SLA ', 'K', 'D.08'),
    ('D.08.K2', 'K2 company policy for contract management ', 'K', 'D.08'),
    ('D.08.K3', 'K3 legal regulations applicable to ICT contracts ', 'K', 'D.08'),
    ('D.08.K4', 'K4 legal issues including IPR ', 'K', 'D.08'),
    ('D.08.K5', 'K5 different service models (SaaS, PaaS, IaaS), service levels and contractual translations (e.g. Cloud Computing) ', 'K', 'D.08'),
    ('D.08.S1', 'S1 foster positive relationships with stakeholders ', 'S', 'D.08'),
    ('D.08.S2', 'S2 negotiate contract terms and conditions ', 'S', 'D.08'),
    ('D.08.S3', 'S3 apply judgment and flexibility in contract negotiations compliant with internal rules and policies ', 'S', 'D.08'),

    ('D.09.K1', 'K1 competence development methods', 'K', 'D.09'),
    ('D.09.K2', 'K2 competence and skill needs analysis methodologies', 'K', 'D.09'),
    ('D.09.K3', 'K3 learning and development support methods (e.g. coaching, teaching)', 'K', 'D.09'),
    ('D.09.K4', 'K4 technology and processes', 'K', 'D.09'),
    ('D.09.K5', 'K5 empowerment techniques', 'K', 'D.09'),
    ('D.09.S1', 'S1 identify competence and skill gaps', 'S', 'D.09'),
    ('D.09.S2', 'S2 identify and recommend work based development opportunities', 'S', 'D.09'),
    ('D.09.S3', 'S3 incorporate within routine work processes, opportunities for skills development', 'S', 'D.09'),
    ('D.09.S4', 'S4 coach', 'S', 'D.09'),
    ('D.09.S5', 'S5 address professional development needs of staff to meet organisational requirements', 'S', 'D.09'),

    ('D.10.K1', 'K1 methods to analyse information and business processes ', 'K', 'D.10'),
    ('D.10.K2', 'K2 ICT devices and tools applicable for the storage and retrieval of data ', 'K', 'D.10'),
    ('D.10.K3', 'K3 challenges related to the size of data sets (e.g. big data) ', 'K', 'D.10'),
    ('D.10.K4', 'K4 challenges related to unstructured data (e.g. data analytics) ', 'S', 'D.10'),
    ('D.10.S1', 'S1 gather internal and external knowledge and information needs ', 'S', 'D.10'),
    ('D.10.S2', 'S2 formalise customer requirements ', 'S', 'D.10'),
    ('D.10.S3', 'S3 translate /reflect business behaviour into structured information ', 'S', 'D.10'),
    ('D.10.S4', 'S4 make information available ', 'S', 'D.10'),
    ('D.10.S5', 'S5 ensure that IPR and privacy issues are respected ', 'S', 'D.10'),
    ('D.10.S6', 'S6 capture, storage, analyse, data sets, that are complex and large, not structured and in different formats ', 'S', 'D.10'),
    ('D.10.S7', 'S7 apply data mining methods ', 'S', 'D.10'),

    ('D.11.K1', 'K1 emerging technologies and the relevant market applications ', 'K', 'D.11'),
    ('D.11.K2', 'K2 business needs ', 'K', 'D.11'),
    ('D.11.K3', 'K3 organisation processes and structures ', 'K', 'D.11'),
    ('D.11.K4', 'K4 customer need analysis techniques ', 'K', 'D.11'),
    ('D.11.K5', 'K5 communication techniques ', 'K', 'D.11'),
    ('D.11.K6', 'K6 “Story telling” techniques ', 'K', 'D.11'),
    ('D.11.S1', 'S1 analyse and formalise business processes ', 'S', 'D.11'),
    ('D.11.S2', 'S2 analyse customer requirements ', 'S', 'D.11'),
    ('D.11.S3', 'S3 present ICT solution cost /benefit ', 'S', 'D.11'),

    ('D.12.K1', 'K1 marketing strategy ', 'K', 'D.12'),
    ('D.12.K2', 'K2 web technologies ', 'K', 'D.12'),
    ('D.12.K3', 'K3 search engine marketing (PPC) ', 'K', 'D.12'),
    ('D.12.K4', 'K4 search engine optimization (SEO) ', 'K', 'D.12'),
    ('D.12.K5', 'K5 mobile marketing (e.g. Pay Per Click) ', 'K', 'D.12'),
    ('D.12.K6', 'K6 social media marketing ', 'K', 'D.12'),
    ('D.12.K7', 'K7 e-mail marketing ', 'K', 'D.12'),
    ('D.12.K8', 'K8 display marketing ', 'K', 'D.12'),
    ('D.12.K9', 'K9 legal issues / requirements ', 'K', 'D.12'),
    ('D.12.S1', 'S1 understand how web technology can be used for marketing purposes ', 'S', 'D.12'),
    ('D.12.S2', 'S2 understand User Centric Marketing ', 'S', 'D.12'),
    ('D.12.S3', 'S3 use and interpret web analytics ', 'S', 'D.12'),
    ('D.12.S4', 'S4 understand the on-line environment', 'S', 'D.12'),

    ('E.01.K1', 'K1 market size and relevant fluctuations ', 'K', 'E.01'),
    ('E.01.K2', 'K2 accessibility of the market according to current conditions (e.g. government policies, emerging technologies, social and cultural trends, etc.) ', 'K', 'E.01'),
    ('E.01.K3', 'K3 the extended supply chain operation ', 'K', 'E.01'),
    ('E.01.K4', 'K4 large scale data analysis techniques (data mining) ', 'K', 'E.01'),
    ('E.01.S1', 'S1 apply what-if techniques to produce realistic outlooks ', 'S', 'E.01'),
    ('E.01.S2', 'S2 generate sales forecasts in relation to current market share ', 'S', 'E.01'),
    ('E.01.S3', 'S3 generate production forecasts taking into account manufacturing capacity ', 'S', 'E.01'),
    ('E.01.S4', 'S4 compare sales and production forecasts and analyse potential mismatches ', 'S', 'E.01'),
    ('E.01.S5', 'S5 interpret external research data and analyse information ', 'S', 'E.01'),

    ('E.02.K1', 'K1 a project methodology, including approaches to define project steps and tools to set up action plans ', 'K', 'E.02'),
    ('E.02.K2', 'K2 technologies to be implemented within the project ', 'K', 'E.02'),
    ('E.02.K3', 'K3 company business strategy and business processes ', 'K', 'E.02'),
    ('E.02.K4', 'K4 development and compliance to financial plans and budgets ', 'K', 'E.02'),
    ('E.02.K5', 'K5 IPR principles and regulation ', 'K', 'E.02'),
    ('E.02.K6', 'K6 structured project management methodologies (e.g. agile techniques) ', 'K', 'E.02'),
    ('E.02.S1', 'S1 identify project risks and define action plans to mitigate ', 'S', 'E.02'),
    ('E.02.S2', 'S2 define a project plan by breaking it down into individual project tasks ', 'S', 'E.02'),
    ('E.02.S3', 'S3 communicate project progress to all relevant parties reporting on topics such as cost control, schedule achievements, quality control, risk avoidance and changes to project specifications ', 'S', 'E.02'),
    ('E.02.S4', 'S4 delegate tasks and manage team member contributions appropriately ', 'S', 'E.02'),
    ('E.02.S5', 'S5 manage external ,contracted resources to achieve project objectives ', 'S', 'E.02'),
    ('E.02.S6', 'S6 optimise project portfolio timelines and delivery objectives by achieving consensus on stakeholder priorities ', 'S', 'E.02'),

    ('E.03.K1', 'K1 corporate values and interests to apply risk analysis taking into account corporate values and interests', 'K', 'E.03'),
    ('E.03.K2', 'K2 the return on investment compared to risk avoidance', 'K', 'E.03'),
    ('E.03.K3', 'K3 good practices (methodologies) and standards in risk analysis', 'K', 'E.03'),
    ('E.03.S1', 'S1 develop risk management plan to identify required preventative actions', 'S', 'E.03'),
    ('E.03.S2', 'S2 communicate and promote the organisation’s risk analysis outcomes and risk management processes', 'S', 'E.03'),
    ('E.03.S3', 'S3 design and document the processes for risk analysis and management', 'S', 'E.03'),
    ('E.03.S4', 'S4 apply mitigation and contingency actions', 'S', 'E.03'),

    ('E.04.K1', 'K1 organisation processes including, decision making, budgets and management structure ', 'K', 'E.04'),
    ('E.04.K2', 'K2 business objectives, own and of other stakeholders ', 'K', 'E.04'),
    ('E.04.K3', 'K3 how to measure and apply resources to meet stakeholder requirements ', 'K', 'E.04'),
    ('E.04.K4', 'K4 business challenges and risks ', 'K', 'E.04'),
    ('E.04.S1', 'S1 deploy empathy to customer needs ', 'S', 'E.04'),
    ('E.04.S2', 'S2 identify potential win win opportunities for customer and own organisation ', 'S', 'E.04'),
    ('E.04.S3', 'S3 establish realistic expectations to support development of mutual trust ', 'S', 'E.04'),
    ('E.04.S4', 'S4 monitor ongoing commitments to ensure fulfilment ', 'S', 'E.04'),
    ('E.04.S5', 'S5 communicate good and bad news to avoid surprises ', 'S', 'E.04'),

    ('E.05.K1', 'K1 research methods, benchmarks and measurements methods ', 'K', 'E.05'),
    ('E.05.K2', 'K2 evaluation, design and implementation methodologies ', 'K', 'E.05'),
    ('E.05.K3', 'K3 existing internal processes ', 'K', 'E.05'),
    ('E.05.K4', 'K4 relevant developments in ICT (e.g. virtualisation, open data, etc.), and the potential impact on processes ', 'K', 'E.05'),
    ('E.05.K5', 'K5 web, cloud and mobile technologies ', 'K', 'E.05'),
    ('E.05.K6', 'K6 resource optimisation and waste reduction ', 'K', 'E.05'),
    ('E.05.S1', 'S1 compose, document and catalogue essential processes and procedures ', 'S', 'E.05'),
    ('E.05.S2', 'S2 propose process changes to facilitate and rationalise improvements ', 'S', 'E.05'),
    ('E.05.S3', 'S3 implement process changes', 'S', 'E.05'),

    ('E.06.K1', 'K1 which methods, tools and procedure are applied within the organisation and where they should be applied ', 'K', 'E.06'),
    ('E.06.K2', 'K2 the IS internal quality audit approach ', 'K', 'E.06'),
    ('E.06.K3', 'K3 regulations and standards in energy efficiency and e-waste ', 'K', 'E.06'),
    ('E.06.S1', 'S1 illustrate how methods, tools and procedures can be applied to implement the organisation’s quality policy ', 'S', 'E.06'),
    ('E.06.S2', 'S2 evaluate and analyse process steps to identify strengths and weaknesses ', 'S', 'E.06'),
    ('E.06.S3', 'S3 assist process owners in the choice and use of measures to evaluate effectiveness and efficiency of the overall process ', 'S', 'E.06'),
    ('E.06.S4', 'S4 monitor, understand and act upon quality indicators ', 'S', 'E.06'),
    ('E.06.S5', 'S5 perform quality audits ', 'S', 'E.06'),

    ('E.07.K1', 'K1 digital strategies ', 'K', 'E.07'),
    ('E.07.K2', 'K2 the impact of business changes on the organisation and human resources ', 'K', 'E.07'),
    ('E.07.K3', 'K3 the impact of business changes on legal issues ', 'K', 'E.07'),
    ('E.07.S1', 'S1 analyse costs and benefits of business changes ', 'S', 'E.07'),
    ('E.07.S2', 'S2 select appropriate ICT solutions based upon benefit, risks and overall impact ', 'S', 'E.07'),
    ('E.07.S3', 'S3 construct and document a plan for implementation of process enhancements ', 'S', 'E.07'),
    ('E.07.S4', 'S4 apply project management standards and tools ', 'S', 'E.07'),

    ('E.08.K1', 'K1 the organisation’s security management policy and its implications for engagement with customers, suppliers and subcontractors ', 'K', 'E.08'),
    ('E.08.K2', 'K2 the best practices and standards in information security management ', 'K', 'E.08'),
    ('E.08.K3', 'K3 the critical risks for information security management ', 'K', 'E.08'),
    ('E.08.K4', 'K4 the ICT internal audit approach ', 'K', 'E.08'),
    ('E.08.K5', 'K5 security detection techniques, including mobile and digital ', 'K', 'E.08'),
    ('E.08.K6', 'K6 cyber attack techniques and counter measures for avoidance ', 'K', 'E.08'),
    ('E.08.K7', 'K7 computer forensics ', 'K', 'E.08'),
    ('E.08.S1', 'S1 document the information security management policy, linking it to business strategy ', 'S', 'E.08'),
    ('E.08.S2', 'S2 analyse the company critical assets and identify weaknesses and vulnerability to intrusion or attack ', 'S', 'E.08'),
    ('E.08.S3', 'S3 establish a risk management plan to feed and produce preventative action plans ', 'S', 'E.08'),
    ('E.08.S4', 'S4 perform security audits ', 'S', 'E.08'),
    ('E.08.S5', 'S5 apply monitoring and testing techniques ', 'S', 'E.08'),
    ('E.08.S6', 'S6 establish the recovery plan ', 'S', 'E.08'),
    ('E.08.S7', 'S7 implement the recovery plan in case of crisis ', 'S', 'E.08'),

    ('E.09.K1', 'K1 the ICT infrastructure and the business organisation ', 'K', 'E.09'),
    ('E.09.K2', 'K2 the business strategy of the company ', 'K', 'E.09'),
    ('E.09.K3', 'K3 the business values ', 'K', 'E.09'),
    ('E.09.K4', 'K4 the legal requirements', 'K', 'E.09'),
    ('E.09.S1', 'S1 manage applicable governance models ', 'S', 'E.09'),
    ('E.09.S2', 'S2 analyse the business context of the company and its evolution ', 'S', 'E.09'),
    ('E.09.S3', 'S3 define and implement appropriate KPI’s ', 'S', 'E.09'),
    ('E.09.S4', 'S4 communicate the value, risks and opportunities derived from the IS strategy ', 'S', 'E.09');
